minimumReleaseAge: 2880

packages:
  - e2e-tests

onlyBuiltDependencies:
  - esbuild

allowBuilds:
  esbuild: set this to true or false

patchedDependencies:
  playwright-core@1.60.0: patches/playwright-core@1.60.0.patch
