name: npm-publish

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: pnpm/action-setup@v6
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run typecheck
      - uses: actions/upload-artifact@v7
        with:
          name: sora-js-sdk-dist
          path: dist/

  npm-publish-canary:
    runs-on: ubuntu-slim
    needs: [build]
    permissions:
      contents: read
      id-token: write
    if: ${{ contains(github.ref, 'canary') }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: sora-js-sdk-dist
          path: dist/

      # pnpm publish は CI では正常に動作しない
      # https://github.com/pnpm/pnpm/issues/4937
      - run: npm install -g npm@latest
      - run: npm publish --no-git-checks --tag canary

  npm-publish:
    runs-on: ubuntu-slim
    needs: [build]
    permissions:
      contents: read
      id-token: write
    if: ${{ !contains(github.ref, 'canary') }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: sora-js-sdk-dist
          path: dist/

      # pnpm publish は CI では正常に動作しない
      # https://github.com/pnpm/pnpm/issues/4937
      - run: npm install -g npm@latest
      - run: npm publish --no-git-checks

  slack_notify:
    needs: [npm-publish-canary, npm-publish]
    runs-on: ubuntu-slim
    if: ${{ !cancelled() }}
    permissions:
      actions: read
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: sora-js-sdk
          notify_mode: failure_and_fixed
