name: test

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "NOTICE"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18", "20"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm --version
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run test
      - run: git diff --stat --exit-code
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: sora-js-sdk
          SLACK_COLOR: danger
          SLACK_TITLE: Failure test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
